trigger: none

parameters:
    - name: ReleaseNotes
      displayName: 'Release Notes (DO NOT USE DOUBLE QUOTES!)'
      type: string
      default: '<Release Notes>'

variables:
    - group: AccessTokens
    - group: Windows
    - group: Android
    - group: TranslatorApp

    - template: templates/pipeline-variables.yml

    - name: 'ReleaseNotesVar'
      value: ${{ parameters.ReleaseNotes }}

stages:
    #********************************************************************************
    # Build the app
    #********************************************************************************
    - stage: Build
      displayName: 'Build Windows and Android apps'

      jobs:
          - template: /.azuredevops/templates/jobs/job-build-apps.yml

    #********************************************************************************
    # Publish apps to Github releases
    #********************************************************************************
    - stage: Publish_To_Github
      displayName: 'Publish apps to Github as a draft release'
      dependsOn: Build
      condition: succeeded()

      jobs:
          - template: /.azuredevops/templates/jobs/job-publish-to-github.yml

    #********************************************************************************
    # Publish Android app to Firebase
    #********************************************************************************
    - stage: Publish_To_Firebase
      displayName: 'Publish Android app to Firebase'
      dependsOn: Build
      condition: succeeded()

      jobs:
          - template: /.azuredevops/templates/jobs/job-publish-to-firebase.yml
