jobs:
    - job: Build
      pool:
          vmImage: windows-latest

          # Uncomment to run on on-prem agent
          #name: Default

      steps:
          - task: PowerShell@2
            displayName: 'PowerShell Script - set buld number variable'
            inputs:
                targetType: 'inline'
                script: |
                    Write-Host "##vso[build.updatebuildnumber]$(major).$(minor).$(Build.BuildId).0"

          - task: PowerShell@2
            displayName: 'PowerShell Script - update version number in project files'
            inputs:
                targetType: filePath
                arguments: "-version '$(Build.BuildNumber)'"
                filePath: './.build/UpdateVersion.ps1'

          - task: PowerShell@2
            displayName: 'Update secrets in appsettings.json'
            inputs:
                targetType: 'inline'
                script: |
                    $file = "$(Build.SourcesDirectory)\source\CopyWords.MAUI\appsettings.json"

                    (Get-Content $file) `
                        -replace '"TranslatorAppUrl":\s*""', '"TranslatorAppUrl": "$(TranslatorAppUrl)"' `
                        -replace '"TranslatorAppRequestCode":\s*""', '"TranslatorAppRequestCode": "$(TranslatorAppRequestCode)"' `
                        -replace '"SyncfusionLicenseKey":\s*""', '"SyncfusionLicenseKey": "$(SyncfusionLicenseKey)"' `
                        -replace '"SentryDsn":\s*""', '"SentryDsn": "$(SentryDsn)"' `
                        -replace '"LaunchDarklyMobileKey":\s*""', '"LaunchDarklyMobileKey": "$(LaunchDarklyMobileKey)"' `
                        -replace '"LaunchDarklyMemberId":\s*""', '"LaunchDarklyMemberId": "$(LaunchDarklyMemberId)"' `
                        -replace '"LatestReleaseUrl":\s*""', '"LatestReleaseUrl": "$(LatestReleaseUrl)"' |
                        Set-Content $file

                    Write-Host "Updated appsettings.json:"
                    Get-Content $file
          - script: yarn install
            displayName: 'yarn install'

          - script: yarn prettier:check
            displayName: 'Check prettier adherence'

          # On a private agent we don't need this
          - task: UseDotNet@2
            inputs:
                packageType: 'sdk'
                version: '$(DOTNET_VERSION)'
            condition: and(succeeded(), eq(variables['Agent.Name'], 'Azure Pipelines 1'))

          # On a private agent we don't need this
          - script: dotnet workload install maui
            displayName: 'Install .NET MAUI Workload'
            condition: and(succeeded(), eq(variables['Agent.Name'], 'Azure Pipelines 1'))

          - template: /.azuredevops/templates/steps-build-windows.yml
          - template: /.azuredevops/templates/steps-build-android.yml

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
                PathtoPublish: '$(build.artifactstagingdirectory)'
